# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: rear_right_leg
  joint_model_group_pose: RR_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - LF_HAA
    - LF_HFE
    - LF_KFE
    - LH_HAA
    - LH_HFE
    - LH_KFE
    - RF_HAA
    - RF_HFE
    - RF_KFE
    - RH_HAA
    - RH_HFE
    - RH_KFE
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: /aww/front_left_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - LF_HAA
      - LF_HFE
      - LF_KFE
  - name: /aww/front_right_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - RF_HAA
      - RF_HFE
      - RF_KFE
  - name: /aww/rear_left_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - LH_HAA
      - LH_HFE
      - LH_KFE
  - name: /aww/rear_right_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - RH_HAA
      - RH_HFE
      - RH_KFE