TrajectoryPlannerROS:
  max_vel_x: 15
  min_vel_x: 0.0
  max_vel_theta: 15
  min_vel_thtea: -15
  min_in_place_vel_theta: 1
  escape_vel: -0.2

  acc_lim_theta: 15
  acc_lim_x: 15

  holonomic_robot: false

  sim_time: 3
  vx_samples: 3
  vy_samples: 0
  vtheta_samples: 20

  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.15

  meter_scoring: true
  path_distance_bias: 4.0
  goal_distance_bias: 1.0
  occdist_scale: 0.01