obstacle_range: 2.5
raytrace_range: 3.0
resolution: 0.1
robot_base_frame: base_footprint
footprint: [[-0.462, 0.3], [0.462, 0.3], [0.462, -0.3], [-0.462, -0.3]]

static:
  map_topic: map
  subscribe_to_updates: true

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: velodyne, data_type: LaserScan, topic: /modified_scan, marking: true, clearing: true}

inflation:
  inflation_radius: 1.5
  cost_scaling_factor: 10

#point_cloud_sensor: {sensor_frame: velodyne_base_link, data_type: PointCloud, topic: /aww/velodyne/points, marking: true, clearing: true}