obstacle_range: 2.5
raytrace_range: 3.0
robot_base_frame: base
footprint: [[-0.462, 0.3], [0.462, 0.3], [0.462, -0.3], [-0.462, -0.3]]
inflation_radius: 0.55

static:
  map_topic: /map
  subscribe_to_updates: true

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: velodyne, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: velodyne_base_link, data_type: PointCloud, topic: /aww/velodyne/points, marking: true, clearing: true}