global_costmap:
  global_frame: map
  rolling_window: false
  robot_base_frame: base_footprint
  update_frequency: 5.0
  transform_tolerance: 1

  plugins:
    - {name: static_map,      type: "costmap_2d::StaticLayer"}
    - {name: obstacles,       type: "costmap_2d::VoxelLayer"}
    - {name: inflation,       type: "costmap_2d::InflationLayer"}