local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  rolling_window: true
  width: 8.0
  height: 8.0
  origin_x: -4
  origin_y: -4
  resolution: 0.05
  transform_tolerance: 1

  plugins:
    - {name: static_map,      type: "costmap_2d::StaticLayer"}
    - {name: obstacles,       type: "costmap_2d::VoxelLayer"}
    - {name: inflation,       type: "costmap_2d::InflationLayer"}