local_costmap:
  global_frame: odom
  robot_base_frame: base
  update_frequency: 10.0
  publish_frequency: 2.0
  rolling_window: true
  width: 6.0
  height: 6.0
  origin_x: -3
  origin_y: -3
  resolution: 0.05
  transform_tolerance: 1

  plugins:
    - {name: obstacles,       type: "costmap_2d::VoxelLayer"}
    - {name: inflation,       type: "costmap_2d::InflationLayer"}

inflation:
  inflation_radius: 0.3