local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: true
  width: 4.0
  height: 4.0
  origin_x: -2
  origin_y: -2
  resolution: 0.1
  transform_tolerance: 1

  plugins:
    - {name: static_map,      type: "costmap_2d::StaticLayer"}
    - {name: obstacles,       type: "costmap_2d::VoxelLayer"}
    - {name: inflation,       type: "costmap_2d::InflationLayer"}