aww:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 

  front_left_leg_controller:
    type: "effort_controllers/JointTrajectoryController"
    action_ns: follow_joint_trajectory
    joints:
      - LF_HAA
      - LF_HFE
      - LF_KFE
    gains:
      LF_HAA: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      LF_HFE: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      LF_KFE: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

    constraints:
      goal_time: &goal_time_constraint 4.5
      stopped_velocity_tolerance: 1.0
      LF_HAA:
        goal: &goal_pos_constraint 0.5
        trajectory: &trajectory_pos_constraint 1.0
      LF_HFE:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      LF_KFE:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint

  front_right_leg_controller:
    type: "effort_controllers/JointTrajectoryController"
    action_ns: follow_joint_trajectory
    joints:
      - RF_HAA
      - RF_HFE
      - RF_KFE
    gains:
      RF_HAA: {p: 1000.0, i: 0.5, d: 0.1, i_clamp: 0.0}
      RF_HFE: {p: 1000.0, i: 0.5, d: 0.1, i_clamp: 0.0}
      RF_KFE: {p: 1000.0, i: 0.5, d: 0.1, i_clamp: 0.0}

    constraints:
      goal_time: *goal_time_constraint
      stopped_velocity_tolerance: 1.0
      RF_HAA:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      RF_HFE:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      RF_KFE:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint

  rear_left_leg_controller:
    type: "effort_controllers/JointTrajectoryController"
    action_ns: follow_joint_trajectory
    joints:
      - LH_HAA
      - LH_HFE
      - LH_KFE
    gains:
      LH_HAA: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      LH_HFE: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      LH_KFE: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

    constraints:
      goal_time: *goal_time_constraint
      stopped_velocity_tolerance: 1.0
      LH_HAA:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      LH_HFE:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      LH_KFE:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint

  rear_right_leg_controller:
    type: "effort_controllers/JointTrajectoryController"
    action_ns: follow_joint_trajectory
    joints:
      - RH_HAA
      - RH_HFE
      - RH_KFE
    gains:
      RH_HAA: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      RH_HFE: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      RH_KFE: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

    constraints:
      goal_time: *goal_time_constraint
      stopped_velocity_tolerance: 1.0
      RH_HAA:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      RH_HFE:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      RH_KFE:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint

  # initial:  # Define initial robot poses.
  # - group: front_left_leg
  #   pose: FL_home
  # - group: front_right_leg
  #   pose: FR_home
  # - group: rear_left_leg
  #   pose: RL_home
  # - group: rear_right_leg
  #   pose: RR_home