aww:

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 

  # Velocity Controllers ---------------------------------------
  aww_velocity_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['LF_wheel', 'LH_wheel']
    right_wheel: ['RF_wheel', 'RH_wheel']
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25

    #k_l: 0.01
    #k_r: 0.01

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    enable_odom_tf: false
    base_frame_id: base

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0
    wheel_separation           : 0.56

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 10.0   # m/s
        has_acceleration_limits: true
        max_acceleration       : 20.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 10.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 50.0   # rad/s^2